apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-app
  namespace: keycloak
  labels:
    app: game-app
spec:
  replicas: 1 # You can adjust the number of replicas based on your requirements
  selector:
    matchLabels:
      app: game-app
  template:
    metadata:
      labels:
        app: game-app
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nc -z postgres-svc 5432; do echo waiting for db; sleep 2; done;",
            ]
      containers:
        - image: {{ .Values.game.image }}
          name: game-app
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: spring-secret
                  key: database_user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: spring-secret
                  key: database_password
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: spring-config
                  key: DATABASE_URL
      dnsPolicy: ClusterFirst
      restartPolicy: Always
