apiVersion: v1
entries:
  gamechart:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-05-26T09:50:18.63028829Z"
    description: A Helm chart for Kubernetes
    digest: ed43e32cfe1a804819142be25833d41b023fb278ef3750611edbde8b0ae51c43
    name: gamechart
    type: application
    urls:
    - https://alsta450.github.io/game-app-helm/charts/gamechart-0.1.0.tgz
    version: 0.1.0
generated: "2024-05-26T09:50:18.629842286Z"
