name: Package and Deploy Helm Chart

on:
  push:
    branches:
      - master  # or any other branch
    # paths:
    #   - 'helm/gamechart/**'  # Adjust path to where your Helm chart is located

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Helm
      uses: azure/setup-helm@v4

    - name: Package Helm Chart
      run: |
        cd helm/gamechart/  # Navigate to the chart directory
        helm package .
        
    - name: Update Helm repository index
      run: |
        cp helm/gamechart/*.tgz charts/
        cd gh-pages
        helm repo index . --url https://${{ github.repository_owner }}.github.io/game-app-helm
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Update Helm chart"
        git push    
        
    - name: Checkout gh-pages branch
      uses: actions/checkout@v2
      with:
        ref: 'gh-pages'  # Switch to gh-pages branch
        path: 'gh-pages'  # Checkout to a different directory
        
    - name: Archive Helm Chart
      uses: actions/upload-artifact@v2
      with:
        name: packaged-chart
        path: '*.tgz'
