name: Package and Deploy Helm Chart

on:
  push:
    branches:
      - master  
    # paths:
    #   - 'helm/gamechart/**'  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Helm
      uses: azure/setup-helm@v4

    - name: Package Helm Chart
      run: |
        cd helm/gamechart/  # Navigate to the chart directory
        helm package .
        
    - name: Update Helm repository index
      run: |
        cp helm/gamechart/*.tgz charts/
        cd charts
        helm repo index . --url https://${{ github.repository_owner }}.github.io/game-app-helm/charts
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Update Helm chart"
        git push  
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        

